### ISSUE TITLE
Border Radius to Foil Container

### ISSUE THREAD

**Issue by rajaarav0** [Zabadam/foil#1]
Is there a way I can provide border radius or alter the shape of Foil widget?

**Comment by Zabadam** [comment]
Any widget that you create with rounded corners may then be provided as the `child` of a `new Foil` widget.

Consider

```dart
return Foil(
  child: SizedBox(
    width: 300,
    height: 300,
    child: DecoratedBox(
      decoration: BoxDecoration(
        // there has to be *something* with which to mask the Foil
        color: Colors.black,
        borderRadius: BorderRadius.circular(25),
      ),
    ),
  ),
);
```
or even

```dart
return Foil(
  child: Text(
    '🔴', // red circle emoji
    style: const TextStyle(fontSize: 200),
  ),
);
```

If the red circle emoji does not appear in the above code, the referenced character is 🔴.

I wrote this comment on mobile without verifying the code.
